### ISSUE TITLE
실행 안되는 문제가 있습니다.

### ISSUE THREAD

**Issue by dinobei** [pokev25/docker-yona#1]
안녕하세요. yona를 docker로 실행해보려하는중에 오류가 발생해서 문의드립니다.
yona build & yona init으로 실행했는데 아래와 같은 오류가 발생하였습니다 (맨 아래에 첨부).

./data/conf/application.conf 파일의 패스워드는 기본인 'password'으로 두어도,  'yonadan'으로 변경하여보아도 아래와 같은 오류가 발생합니다.

docker-compose.yml 에서 볼륨 부분은 아래와 같이 수정한 상태인데, /usr/local/yona-data 폴더에 ./data 폴더 내용을 그대로 복사해야하나요? 아니면 자동으로 복사되는건지.. 둘 다 실험해봐도 동일한 오류가 발생합니다.

```
volumes:
      - ./data:/usr/local/yona-data
```

*** [Run] ***
*** [RUN BEFORE_SCRIPT] ***
*** [DONE BEFORE_SCRIPT] ***
*** Straing container yona bin ... ***
Play server process ID is 9
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused).Message:Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:132)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91)
	at org.mariadb.jdbc.Driver.connect(Driver.java:109)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	... 22 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:815)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
	... 28 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:383)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
	... 30 more
*** [RUN BEFORE_SCRIPT] ***
*** [DONE BEFORE_SCRIPT] ***
*** Straing container yona bin ... ***
*** [Done] ***

**Comment by pokev25** [comment]
에러메시지를 보면
```
Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused
```
도커에서 접속할 DB정보가 맞지 않아서 그렇습니다.
도커 외부의 IP정보를 입력하시면 동작할 것 같습니다.

**Comment by pokev25** [comment]
HOST의 IP를 입력 하면 됩니다.

설정 관련 사항은 요나의 위키를 참고 하세요.

https://github.com/yona-projects/yona/wiki
